### ISSUE TITLE
get_forces() function

### ISSUE THREAD

**Issue by burbanom** [SINGROUP/pycp2k#1]
Hello, 

I am interested in using pycp2k for my research and I have seen that it was possible to extract the forces from a calculation using something like calc.get_forces(), however I can't seem to find this functionality anymore in the master release of the package. Has the way of accessing this feature changed or is it not available anymore?

MB

**Comment by lauri-codes** [comment]
Hi!

The get_forces() function was removed because it could return invalid results in some cases. It worked fine for single-point calculations if the output included only one calculation. Currently the plan is to leave all the analysis to the user, because pycp2k cannot reliably do the analysis for all cases.

If you want to get the forces from the output you must write your own analysis code. I would suggest using a regular expression library (e.g. python's [builtin re module](https://docs.python.org/2/library/re.html)) for getting the results from the output file.

**Comment by burbanom** [comment]
OK, thanks for the information!
